environment:
  nodejs_version: "10"

matrix:
  fast_finish: true

install:
  - ps: Install-Product node $env:nodejs_version
  - node --version
  - npm install

test_script:
  - npm test

build: off
deploy: off

skip_branch_with_pr: true

cache:
  - node_modules