environment:
  nodejs_version: "10"

matrix:
  fast_finish: true

skip_tags: true
skip_branch_with_pr: true

install:
  - ps: Install-Product node $env:nodejs_version
  - node --version
  - npm install

test_script:
  - npm test

build: off
deploy: off

cache:
  - node_modules
